# Generated by Django 5.2.1 on 2025-06-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='设置键')),
                ('value', models.JSONField(verbose_name='设置值')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.FileField(upload_to='backups/', verbose_name='备份文件')),
                ('backup_type', models.CharField(choices=[('full', '完整备份'), ('database', '数据库备份'), ('files', '文件备份'), ('settings', '设置备份')], max_length=20, verbose_name='备份类型')),
                ('size', models.BigIntegerField(verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.TextField(blank=True, verbose_name='备份说明')),
                ('is_auto', models.BooleanField(default=False, verbose_name='是否自动备份')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '系统备份',
                'verbose_name_plural': '系统备份',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重错误')], default='info', max_length=10, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('module', models.CharField(max_length=100, verbose_name='模块')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='system_sett_level_fc1feb_idx'), models.Index(fields=['module', 'created_at'], name='system_sett_module_0886b9_idx'), models.Index(fields=['user', 'created_at'], name='system_sett_user_id_7f7aa6_idx')],
            },
        ),
    ]
