# Generated by Django 5.2.1 on 2025-06-04 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '工艺类别',
                'verbose_name_plural': '工艺类别',
            },
        ),
        migrations.CreateModel(
            name='ProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('changes', models.JSONField(default=dict, verbose_name='变更内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '工艺历史',
                'verbose_name_plural': '工艺历史',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='工艺名称')),
                ('description', models.TextField(verbose_name='工艺描述')),
                ('parameters', models.JSONField(default=dict, verbose_name='工艺参数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '激活'), ('inactive', '停用')], default='draft', max_length=20, verbose_name='状态')),
                ('grinding_speed', models.FloatField(blank=True, null=True, verbose_name='磨削速度 (rpm)')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='压力 (bar)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度 (°C)')),
                ('processing_time', models.IntegerField(blank=True, null=True, verbose_name='加工时间 (分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.processcategory', verbose_name='工艺类别')),
            ],
            options={
                'verbose_name': '工艺数据',
                'verbose_name_plural': '工艺数据',
                'ordering': ['-created_at'],
            },
        ),
    ]
