# Generated by Django 5.2.1 on 2025-06-06 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolishingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(max_length=50, unique=True, verbose_name='工艺编号')),
                ('process_name', models.CharField(max_length=200, verbose_name='工艺名称')),
                ('process_type', models.CharField(choices=[('wet', '湿式光整'), ('dry', '干式光整'), ('compound', '复合光整'), ('custom', '自定义工艺')], max_length=20, verbose_name='工艺类型')),
                ('description', models.TextField(blank=True, verbose_name='工艺描述')),
                ('applicable_materials', models.JSONField(default=list, verbose_name='适用材料')),
                ('applicable_part_types', models.JSONField(default=list, verbose_name='适用零件类型')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='加工时间(分钟)')),
                ('rotation_speed', models.FloatField(blank=True, null=True, verbose_name='转速(rpm)')),
                ('vibration_frequency', models.FloatField(blank=True, null=True, verbose_name='振动频率(Hz)')),
                ('liquid_ratio', models.CharField(blank=True, max_length=100, verbose_name='液体配比')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度(°C)')),
                ('abrasive_type', models.CharField(blank=True, max_length=100, verbose_name='磨料类型')),
                ('abrasive_size', models.CharField(blank=True, max_length=50, verbose_name='磨料粒度')),
                ('abrasive_quantity', models.FloatField(blank=True, null=True, verbose_name='磨料用量(kg)')),
                ('chemical_agents', models.JSONField(default=list, verbose_name='化学剂配方')),
                ('quality_criteria', models.JSONField(default=dict, verbose_name='质量标准')),
                ('expected_surface_roughness', models.FloatField(blank=True, null=True, verbose_name='预期表面粗糙度(μm)')),
                ('safety_precautions', models.TextField(blank=True, verbose_name='安全注意事项')),
                ('environmental_requirements', models.TextField(blank=True, verbose_name='环境要求')),
                ('material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='材料成本')),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='人工成本')),
                ('equipment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='设备成本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('under_review', '审核中'), ('approved', '已批准'), ('rejected', '已拒绝'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='版本号')),
                ('is_standard', models.BooleanField(default=False, verbose_name='是否为标准工艺')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_processes', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_processes', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_processes', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '光整工艺',
                'verbose_name_plural': '光整工艺',
                'db_table': 'polishing_processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='processes/attachments/', verbose_name='附件文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('document', '文档'), ('video', '视频'), ('drawing', '图纸'), ('other', '其他')], max_length=20, verbose_name='文件类型')),
                ('file_size', models.IntegerField(verbose_name='文件大小(字节)')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='polishing_processes.polishingprocess', verbose_name='关联工艺')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '工艺附件',
                'verbose_name_plural': '工艺附件',
                'db_table': 'process_attachments',
            },
        ),
        migrations.CreateModel(
            name='ProcessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '拒绝'), ('needs_revision', '需要修改')], max_length=20, verbose_name='审核状态')),
                ('comments', models.TextField(blank=True, verbose_name='审核意见')),
                ('technical_score', models.IntegerField(blank=True, null=True, verbose_name='技术评分(1-10)')),
                ('safety_score', models.IntegerField(blank=True, null=True, verbose_name='安全评分(1-10)')),
                ('cost_score', models.IntegerField(blank=True, null=True, verbose_name='成本评分(1-10)')),
                ('overall_score', models.FloatField(blank=True, null=True, verbose_name='综合评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='polishing_processes.polishingprocess', verbose_name='关联工艺')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '工艺审核记录',
                'verbose_name_plural': '工艺审核记录',
                'db_table': 'process_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100, verbose_name='零件名称')),
                ('part_number', models.CharField(max_length=50, verbose_name='零件编号')),
                ('quantity', models.IntegerField(verbose_name='加工数量')),
                ('actual_processing_time', models.FloatField(blank=True, null=True, verbose_name='实际加工时间(分钟)')),
                ('actual_surface_roughness', models.FloatField(blank=True, null=True, verbose_name='实际表面粗糙度(μm)')),
                ('quality_rating', models.IntegerField(blank=True, null=True, verbose_name='质量评分(1-10)')),
                ('notes', models.TextField(blank=True, verbose_name='使用备注')),
                ('actual_material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际材料成本')),
                ('actual_labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际人工成本')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='polishing_processes.polishingprocess', verbose_name='使用的工艺')),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '工艺使用记录',
                'verbose_name_plural': '工艺使用记录',
                'db_table': 'process_usage_records',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='步骤序号')),
                ('step_name', models.CharField(max_length=100, verbose_name='步骤名称')),
                ('description', models.TextField(verbose_name='步骤描述')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='持续时间(分钟)')),
                ('parameters', models.JSONField(default=dict, verbose_name='步骤参数')),
                ('quality_checkpoints', models.JSONField(default=list, verbose_name='质量检查点')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='polishing_processes.polishingprocess', verbose_name='关联工艺')),
            ],
            options={
                'verbose_name': '工艺步骤',
                'verbose_name_plural': '工艺步骤',
                'db_table': 'process_steps',
                'ordering': ['process', 'step_number'],
                'unique_together': {('process', 'step_number')},
            },
        ),
    ]
