# Generated by Django 5.2.1 on 2025-06-06 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=200, verbose_name='试验名称')),
                ('experiment_purpose', models.TextField(verbose_name='试验目的')),
                ('experiment_method', models.TextField(verbose_name='试验方法')),
                ('test_material', models.CharField(max_length=100, verbose_name='试验材料')),
                ('test_parameters', models.JSONField(default=dict, verbose_name='试验参数')),
                ('test_results', models.JSONField(blank=True, default=dict, verbose_name='试验结果')),
                ('conclusion', models.TextField(blank=True, verbose_name='试验结论')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='试验状态')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('experimenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='试验人员')),
            ],
            options={
                'verbose_name': '试验数据',
                'verbose_name_plural': '试验数据',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='知识标题')),
                ('knowledge_type', models.CharField(choices=[('best_practice', '最佳实践'), ('troubleshooting', '故障排除'), ('parameter_optimization', '参数优化'), ('material_guide', '材质指南')], max_length=30, verbose_name='知识类型')),
                ('content', models.TextField(verbose_name='知识内容')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='关键词')),
                ('expert_name', models.CharField(max_length=100, verbose_name='专家姓名')),
                ('expert_title', models.CharField(max_length=100, verbose_name='专家职称')),
                ('applicable_scenarios', models.TextField(verbose_name='适用场景')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
            ],
            options={
                'verbose_name': '专家知识',
                'verbose_name_plural': '专家知识库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='案例名称')),
                ('description', models.TextField(blank=True, verbose_name='案例描述')),
                ('part_material', models.CharField(max_length=100, verbose_name='零件材质')),
                ('part_size', models.CharField(max_length=100, verbose_name='零件尺寸')),
                ('surface_requirement', models.CharField(max_length=200, verbose_name='表面要求')),
                ('grinding_media', models.CharField(max_length=100, verbose_name='研磨介质')),
                ('grinding_compound', models.CharField(max_length=100, verbose_name='研磨剂')),
                ('rotation_speed', models.FloatField(verbose_name='转速(rpm)')),
                ('processing_time', models.FloatField(verbose_name='加工时间(分钟)')),
                ('vibration_frequency', models.FloatField(blank=True, null=True, verbose_name='振动频率(Hz)')),
                ('surface_roughness_before', models.FloatField(blank=True, null=True, verbose_name='加工前表面粗糙度(Ra)')),
                ('surface_roughness_after', models.FloatField(blank=True, null=True, verbose_name='加工后表面粗糙度(Ra)')),
                ('removal_amount', models.FloatField(blank=True, null=True, verbose_name='去除量(μm)')),
                ('quality_grade', models.CharField(blank=True, max_length=10, verbose_name='质量等级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '工艺实例',
                'verbose_name_plural': '工艺实例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('deburring', '去毛刺'), ('polishing', '抛光'), ('cleaning', '清洗'), ('surface_treatment', '表面处理')], max_length=30, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('standard_media', models.CharField(max_length=100, verbose_name='标准研磨介质')),
                ('standard_compound', models.CharField(max_length=100, verbose_name='标准研磨剂')),
                ('standard_speed', models.FloatField(verbose_name='标准转速(rpm)')),
                ('standard_time', models.FloatField(verbose_name='标准时间(分钟)')),
                ('applicable_materials', models.TextField(verbose_name='适用材质')),
                ('applicable_sizes', models.TextField(verbose_name='适用尺寸范围')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '工序模板',
                'verbose_name_plural': '工序模板',
                'ordering': ['-created_at'],
            },
        ),
    ]
