# Generated by Django 5.2.1 on 2025-06-04 12:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrindingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_no', models.CharField(max_length=50, unique=True, verbose_name='磨块编号')),
                ('block_name', models.CharField(max_length=100, verbose_name='磨块名称')),
                ('block_type', models.CharField(max_length=50, verbose_name='磨块类型')),
                ('block_brand', models.CharField(max_length=50, verbose_name='磨块牌号')),
                ('block_factory', models.CharField(max_length=100, verbose_name='磨块厂家')),
                ('block_shape', models.CharField(max_length=50, verbose_name='磨块形状')),
                ('block_spec', models.CharField(max_length=100, verbose_name='磨块规格')),
                ('block_material', models.CharField(max_length=50, verbose_name='磨块材质')),
                ('block_color', models.CharField(max_length=50, verbose_name='磨块颜色')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='重量(g)')),
                ('wear_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='磨耗率(%)')),
                ('grinding_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='磨削率(%)')),
                ('batch', models.CharField(blank=True, max_length=50, verbose_name='批次')),
                ('feature1', models.CharField(blank=True, max_length=200, verbose_name='特征信息1')),
                ('feature2', models.CharField(blank=True, max_length=200, verbose_name='特征信息2')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_blocks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '磨块信息',
                'verbose_name_plural': '磨块信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除')], max_length=20, verbose_name='操作类型')),
                ('changes', models.JSONField(default=dict, verbose_name='变更内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='grinding_blocks.grindingblock', verbose_name='磨块')),
            ],
            options={
                'verbose_name': '磨块历史',
                'verbose_name_plural': '磨块历史',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='grindingblock',
            index=models.Index(fields=['block_no'], name='grinding_bl_block_n_30bb1d_idx'),
        ),
        migrations.AddIndex(
            model_name='grindingblock',
            index=models.Index(fields=['block_type'], name='grinding_bl_block_t_57eaff_idx'),
        ),
        migrations.AddIndex(
            model_name='grindingblock',
            index=models.Index(fields=['block_factory'], name='grinding_bl_block_f_476b56_idx'),
        ),
        migrations.AddIndex(
            model_name='grindingblock',
            index=models.Index(fields=['created_at'], name='grinding_bl_created_7ce19d_idx'),
        ),
    ]
