# Generated by Django 5.2.1 on 2025-06-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='企业名称'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry_role',
            field=models.CharField(blank=True, max_length=100, verbose_name='产业链角色'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('system_admin', '系统管理员'), ('process_engineer', '工艺工程师'), ('equipment_operator', '设备操作员'), ('quality_inspector', '质量检测员'), ('enterprise_admin', '企业管理员')], default='equipment_operator', max_length=20, verbose_name='用户类型'),
        ),
    ]
