# Generated by Django 5.2.1 on 2025-06-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_position_customuser_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(
                choices=[
                    ('system_admin', '系统管理员'),
                    ('process_engineer', '工艺工程师'),
                    ('equipment_operator', '设备操作员'),
                    ('quality_inspector', '质量检测员'),
                    ('enterprise_admin', '企业管理员')
                ],
                default='equipment_operator',
                max_length=20,
                verbose_name='用户类型'
            ),
        ),
    ]
