# Generated by Django 5.2.1 on 2025-06-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('model', models.CharField(max_length=100, verbose_name='设备型号')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='序列号')),
                ('status', models.CharField(choices=[('running', '运行中'), ('idle', '空闲'), ('maintenance', '维护中'), ('error', '故障'), ('offline', '离线')], default='offline', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=10, verbose_name='优先级')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
                ('workshop', models.CharField(max_length=100, verbose_name='车间')),
                ('specifications', models.JSONField(default=dict, verbose_name='技术规格')),
                ('max_speed', models.FloatField(blank=True, null=True, verbose_name='最大转速 (rpm)')),
                ('max_pressure', models.FloatField(blank=True, null=True, verbose_name='最大压力 (bar)')),
                ('power_rating', models.FloatField(blank=True, null=True, verbose_name='额定功率 (kW)')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='保修到期')),
                ('last_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='上次维护时间')),
                ('next_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='下次维护时间')),
                ('total_runtime', models.FloatField(default=0, verbose_name='总运行时间 (小时)')),
                ('total_cycles', models.IntegerField(default=0, verbose_name='总运行周期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], max_length=10, verbose_name='警告级别')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='警告信息')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='已解决')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设备警告',
                'verbose_name_plural': '设备警告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', '例行维护'), ('preventive', '预防性维护'), ('corrective', '修正性维护'), ('emergency', '紧急维护')], max_length=20, verbose_name='维护类型')),
                ('description', models.TextField(verbose_name='维护描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='维护成本')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '维护记录',
                'verbose_name_plural': '维护记录',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='设备类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
            },
        ),
    ]
