# Generated by Django 5.2.1 on 2025-06-06 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolishingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=50, unique=True, verbose_name='需求编号')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('description', models.TextField(verbose_name='需求描述')),
                ('part_name', models.CharField(max_length=100, verbose_name='零件名称')),
                ('part_number', models.CharField(max_length=50, verbose_name='零件编号')),
                ('material', models.CharField(max_length=100, verbose_name='材料')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('surface_roughness_before', models.FloatField(blank=True, null=True, verbose_name='初始表面粗糙度(μm)')),
                ('surface_roughness_after', models.FloatField(blank=True, null=True, verbose_name='目标表面粗糙度(μm)')),
                ('dimensional_tolerance', models.CharField(blank=True, max_length=100, verbose_name='尺寸公差')),
                ('geometric_tolerance', models.CharField(blank=True, max_length=100, verbose_name='几何公差')),
                ('special_requirements', models.TextField(blank=True, verbose_name='特殊要求')),
                ('technical_drawings', models.FileField(blank=True, null=True, upload_to='requirements/drawings/', verbose_name='技术图纸')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('under_review', '审核中'), ('approved', '已批准'), ('rejected', '已拒绝'), ('in_progress', '进行中'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('urgency_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=10, verbose_name='紧急程度')),
                ('required_completion_date', models.DateField(blank=True, null=True, verbose_name='要求完成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polishing_requirements', to=settings.AUTH_USER_MODEL, verbose_name='需求提出者')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requirements', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '光整需求',
                'verbose_name_plural': '光整需求',
                'db_table': 'polishing_requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requirements/attachments/', verbose_name='附件文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.IntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='polishing_requirements.polishingrequirement', verbose_name='关联需求')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '需求附件',
                'verbose_name_plural': '需求附件',
                'db_table': 'requirement_attachments',
            },
        ),
        migrations.CreateModel(
            name='RequirementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_internal', models.BooleanField(default=False, verbose_name='内部评论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='polishing_requirements.polishingrequirement', verbose_name='关联需求')),
            ],
            options={
                'verbose_name': '需求评论',
                'verbose_name_plural': '需求评论',
                'db_table': 'requirement_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('template_data', models.JSONField(verbose_name='模板数据')),
                ('category', models.CharField(max_length=50, verbose_name='模板分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '需求模板',
                'verbose_name_plural': '需求模板',
                'db_table': 'requirement_templates',
                'ordering': ['category', 'template_name'],
            },
        ),
    ]
